### ISSUE TITLE
Redemption App

### ISSUE THREAD

**Issue by yeqbfgxjiq** [aragoncoop/ideas#1]
A simple (TPS?) app where you burn tokens for a proportional amount of some collateral in a vault (this is essentially the rage quit mechanism in moloch).

**Comment by lkngtn** [comment]
Can we change the title of this to "Redemption App" or similar to avoid confusion with the moloch feature since it may turn out to be significantly different. 

The requirements would be pretty simple:

1. The app would be initialized with a `vault` address and a `minime token` address
2. The app would have configurable list of token addresses
3. Users could burn any amount of `minime token` and be transferred a proportional amount of the balances in the `vault` for each token address in the list. 

For example if there are a total of 100 Merit tokens in the supply, and I "redeem" 10, I would be transferred 10% of the balance in the vault of each token in the list.

**Comment by 0xGabi** [comment]
Really interesting, excited to make this happen 🙌

**Comment by yeqbfgxjiq** [comment]
[1Hive](https://1hive.org/) is [building](https://github.com/1Hive/redemptions-app/) this.
